services:

  nginx:
    image: nginx:1.11
    tty: true
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_PATH}:${APP_CONTAINER_PATH}
    links:
      - php
    ports:
      - ${APP_PORT}:80

  php:
    build:
      context: ./.docker/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
    tty: true
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    volumes:
      - ./.docker/php/conf/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf:ro
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini:ro
      - ${APP_PATH}:${APP_CONTAINER_PATH}
    environment:
      XDEBUG_FILE_LINK_FORMAT: ${XDEBUG_FILE_LINK_FORMAT:-}
      PHP_CS_FIXER_IGNORE_ENV: true
    links:
      - mariadb

  client:
    image: node:22.6
    tty: true
    working_dir: ${APP_CONTAINER_PATH}/client
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    command: yarn run start
    volumes:
      - ${APP_PATH}:${APP_CONTAINER_PATH}
    env_file:
      - client/.env

  mariadb:
    image: mariadb:10
    tty: true
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      APP_USER_ID: ${APP_USER_ID}
      APP_GROUP_ID: ${APP_GROUP_ID}
    working_dir: ${APP_CONTAINER_PATH}
    volumes:
      - mariadb:/var/lib/mysql
      - ./.docker/mysql/scripts/reset:/usr/local/bin/reset
      - ./.docker/mysql/scripts/save:/usr/local/bin/save
      - ./.docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ${APP_PATH}:${APP_CONTAINER_PATH}

volumes:
  mariadb: ~
